# Site settings
title: Fawwaz blog
email: 
description: "Hidup hanya sekali, justeru biarlah bererti"
baseurl: ""
url: "http://knabenphysik.github.io"
twitter_username: kuarkdelima
github_username:  knabenphysik

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
